Some updates now that 0.9.0 is out

diff --git a/kc b/kc
--- a/kc
+++ b/kc
@@ -5,6 +5,13 @@
 DOC="https://github.com/jorgemoralespou/kind-wrapper/blob/master/README.adoc"
 SCRIPT_NAME=$(basename "$0")
 KIND_BIN='/usr/local/bin/kind'
+YTT_BIN='/usr/local/bin/ytt'
+KUBECTL_BIN='/usr/local/bin/kubectl'
+DOCKER_BIN='/usr/local/bin/docker'
+
+CONFIRM=${CONFIRM:-""}
+VERIFY=${VERIFY:-""}
+UNINSTALL=${UNINSTALL:-""}
 
 # Handle source locations that might be a symlink (ref: http://bit.ly/2kcvSCS)
 SOURCE="${BASH_SOURCE[0]}"
@@ -15,6 +22,11 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
+#
+# Colors for echo
+# 
+RED='\033[0;31m'
+NC='\033[0m' # No Color
 
 KC_HOME=$HOME/.kc
 KC_PROFILES_HOME=$KC_HOME/profiles
@@ -24,7 +36,20 @@ KC_PROFILES_HOME=$KC_HOME/profiles
 
 
 # DEFAULTS:
-__VERSION="1.18.2"
+__VERSION="1.19.1"
+
+
+function whichClusterIsRunning {
+  # TODO: Properly get cluster name
+  local __clusters=$(kind get clusters)
+  for clustername in $__clusters
+  do
+    if [[ "x$(docker ps -f name=$clustername -q)" != "x" ]]; then
+      echo "$clustername"
+    fi
+  done
+}
+
 
 # Commands:
 #
@@ -80,26 +105,27 @@ function up {
   # TODO: Make selection of "cluster configs/profiles". By default it will be basic
   local CLUSTER_CONFIG="basic"
 
+  # TODO: Check this kind scripts: https://github.com/kameshsampath/jo/tree/master/bin
+
   # Build command line
   # Test if profile file exists, and if not, create it
   local CMDLINE=""
   if [ ! -e "$KC_PROFILES_HOME/${_profile}.yaml" ]; then
     # Create profile file
-    PROCESSED_TEMPLATE=$(ytt -v name=${_profile} -f $DIR/internal/$CLUSTER_CONFIG.yaml -f $DIR/internal/values.yaml > $KC_PROFILES_HOME/${_profile}.yaml)
+    PROCESSED_TEMPLATE=$(${YTT_BIN} -v name=${_profile} -f $DIR/internal/$CLUSTER_CONFIG.yaml -f $DIR/internal/values.yaml > $KC_PROFILES_HOME/${_profile}.yaml)
     RET_VALUE=$?
     [ "$RET_VALUE" != 0 ] && echo "[ERROR] Creating cluster configuration" && return 1
     echo "[INFO] Cluster config created in $KC_PROFILES_HOME/${_profile}.yaml)"
-    # TODO: Once 0.9.0 is out and kind config can provide a name, remove the argument
-    CMDLINE="${KIND_BIN} create cluster --name=${_profile} --config=$KC_PROFILES_HOME/${_profile}.yaml"
+    CMDLINE="${KIND_BIN} create cluster --config=$KC_PROFILES_HOME/${_profile}.yaml"
   else
-    CMDLINE="docker start ${_profile}-control-plane"
-    kubectl config use-context kind-${_profile}
+    CMDLINE="${DOCKER_BIN} start ${_profile}-control-plane"
+    ${KUBECTL_BIN} config use-context kind-${_profile}
   fi
-  
-##  [ ! -z "$__PARM_VERSION" ] && CMDLINE+=" --version $__PARM_VERSION" || CMDLINE+=" --version $__VERSION"
+
+# TODO: See how we can specify the version 
+#  [ ! -z "$__PARM_VERSION" ] && CMDLINE+=" --version $__PARM_VERSION" || CMDLINE+=" --version $__VERSION"
 
   echo "[INFO] $CMDLINE"
-  echo "[INFO] Cluster name is not yet supported in 0.8.1"
   eval "$CMDLINE"
 
   return 0
@@ -109,7 +135,7 @@ function up.help {
   echo "Starts/Creates a cluster with the given profile name (or default)"
   echo "in case no profile is specified"
   echo ""
-  echo "Profile information will be stored in $OPENSHIFT_PROFILES_DIR/<PROFILE>"
+  echo "Profile information will be stored in $KC_PROFILES_HOME/<PROFILE>"
   echo ""
   echo "Usage:"
   echo " $SCRIPT_NAME up [<profile>] [<args>]"
@@ -139,8 +165,9 @@ function down {
     shift # Remove profile name
   fi
 
-  docker stop ${_profile}-control-plane
-  kubectl config unset current-context 
+  ${DOCKER_BIN} stop ${_profile}-control-plane
+  # TODO: Only unset if it was selected as current context
+  ${KUBECTL_BIN} config unset current-context 
 }
 
 function down.help {
@@ -158,10 +185,20 @@ function down.help {
 #  $1: [-s] silent
 function status {
   [ "$1" == "-h" ] || [ "$1" == "--help" ] && ${FUNCNAME[0]}.help && return 0
+  # TODO: Get profile
+  _profile=$(whichClusterIsRunning)
 
-  [[ "$(docker ps -f name=origin -q)" == "" ]] && echo "no cluster running" && return 1
-  echo "oc cluster running. Current profile <$([ -f $OPENSHIFT_HOME_DIR/active_profile ] && cat $OPENSHIFT_HOME_DIR/active_profile || echo 'unknown')>"
-  ${OC_BINARY} cluster status
+  local running_cluster=$(${DOCKER_BIN} ps -q -f "name=${_profile}*" -f "status=running")
+  if [[ "${running_cluster}" == "" ]]; then
+    echo "no cluster running"
+  else
+    echo "Cluster ${_profile} is running"
+    return 1
+  fi
+  # local stopped_cluster=$(${DOCKER_BIN} ps -q -f "name=${_profile}*" -f "status=exited")
+  # [[ "${stopped_cluster}" == "" ]] && echo "no cluster stopped" && return 1
+#  echo "oc cluster running. Current profile <$([ -f $KC_HOME/active_profile ] && cat $KC_HOME/active_profile || echo 'unknown')>"
+#  ${OC_BINARY} cluster status
 
   return 0
 }
@@ -182,7 +219,7 @@ function delete {
   [ "$1" == "-h" ] || [ "$1" == "--help" ] && ${FUNCNAME[0]}.help && return 0
   [ "$1" == "-c" ] || [ "$1" == "--confirm" ] && CONFIRM=true && shift
 
-  local _profile="$1"
+  local _profile=$(whichClusterIsRunning)
   #TODO: Check that cluster with name is not already running
 #  status &> /dev/null && error_exit "There is a cluster already running. You can not run 2 cluster at the same time"
 
@@ -197,6 +234,8 @@ function delete {
   echo "[INFO] ${KIND_BIN} delete cluster --name ${_profile}"
   ${KIND_BIN} delete cluster --name ${_profile}
   rm -rf $KC_PROFILES_HOME/${_profile}.yaml
+  # TODO: Only unset if it was selected as current context
+  # TODO: Delete context in .kube/config
 }
 
 function delete.help {
@@ -204,7 +243,7 @@ function delete.help {
   echo "if none is specified. Use -c/--confirm to skip confirmation prompt"
   echo ""
   echo "All the information store for the profile will be removed"
-  echo "- This information is stored in $OPENSHIFT_PROFILES_DIR/<PROFILE>"
+  echo "- This information is stored in $KC_PROFILES_HOME/<PROFILE>"
   echo "- Also the profile will be cleared from the .kubeconfig file"
   echo "- All the images created by this cluster will be removed"
   echo ""
@@ -227,7 +266,7 @@ function list {
 function list.help {
   echo "List all the available profiles"
   echo ""
-  echo "Profiles are located in $OPENSHIFT_PROFILES_DIR"
+  echo "Profiles are located in $KC_PROFILES_HOME"
   echo ""
   echo "Usage:"
   echo " $SCRIPT_NAME list"
@@ -250,37 +289,138 @@ function help {
   echo "See the documentation at $DOC"
 }
 
-# Use -gt 1 to consume two arguments per pass in the loop (e.g. each
-# argument has a corresponding value to go with it).
-# Use -gt 0 to consume one or more arguments per pass in the loop (e.g.
-# some arguments don't have a corresponding value to go with it such
-# as in the --default example).
+function install_ingress {
+  local __addon="ingress"
+  echo "installing $__addon"
+  # Check that cluster is running
+  # Check that we're using the right context
+  # Prompt for confirmation
+  if [ -n "$CONFIRM" ] && [ "$CONFIRM" == "true" ] ; then
+    reply="y"
+  else
+    echo -e "Cluster: ${RED}${CLUSTER}${NC}"
+    echo -e "Configuration: ${RED}${OVERRIDE_FILE}${NC}"
+    echo -e "Overlay: ${RED}${OVERLAY_FILE}${NC}"
+    echo ""
+    echo -e "Are you sure you want to install an $step with the following values? (y/n)"
+    read -n 1 -r reply
+    echo # move to a new line
+  fi
+  # Install
+  if [[ $reply =~ ^[Yy]$ ]] ; then
+    if [ ! -z $UNINSTALL ] ; then
+      kapp delete -a $__addon -n default -y
+    else
+      # TODO: Get current profile name
+      ytt -f internal/addons/$__addon --ignore-unknown-comments | kapp deploy -a $__addon -n default --kubeconfig-context kind-test -y -f -
+
+      # We can test ingress using this: https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress
+      # But with ingress configured, we have it available at: test.127.0.0.1.nip.io 
+    fi
+  else
+    echo "Installation cancelled"
+    exit 1
+  fi
+}
+
+function install {
+  if [[ $# -gt 0 ]]
+  then
+    key="$1"
+    case $key in
+      ingress)
+        install_ingress
+        ;;
+      *)
+        echo "Can't install addon $key"
+        ;;
+    esac
+  else
+    echo "Missing addont to install"
+  fi
+}
+
+function parse_args {
+  while [[ $# -gt 0 ]]
+  do
+    local key="$1"
+    case $key in
+      -h|--help)
+        SHOW_HELP="true"
+        shift # past argument
+        ;;
+      -v|--verify)
+        VERIFY="true"
+        shift # past argument
+        ;;
+      -f|--file)
+        OVERRIDE_FILE="$2"
+        shift # past argument
+        shift # past value
+        ;;
+      -f=*|--file=*)
+        OVERRIDE_FILE="${i#*=}"
+        shift # past argument
+        ;;
+      -o|--overlay)
+        OVERLAY_FILE="$2"
+        shift # past argument
+        shift # past value
+        ;;
+      -o=*|--overlay=*)
+        OVERLAY_FILE="${i#*=}"
+        shift # past value
+        ;;
+      -c|--confirm)
+        CONFIRM="true"
+        shift # past argument
+        ;;
+      -u|--uninstall)
+        UNINSTALL="true"
+        shift # past argument
+        ;;
+      *)
+        echo "Wrong argument $key. Not supported"
+        exit 1
+        ;;
+    esac
+  done
+#  echo "SHOW_HELP=$SHOW_HELP"
+#  echo "OVERRIDE_FILE=$OVERRIDE_FILE"
+#  echo "OVERLAY_FILE=$OVERLAY_FILE"
+#  echo "CONFIRM=$CONFIRM"
+}
+
 if [[ $# -gt 0 ]]
 then
-   key="$1"
-   case $key in
-      up)
-        shift # past argument
-        up "$@"
-        ;;
-      down)
-        shift # past argument
-        down "$@"
-        ;;
-      delete)
-        shift # past argument
-        delete "$@"
-        ;;
-      list)
-        list
-        ;;
-      status)
-        status
-        ;;
-      -h|--help)
-        help
-        ;;
-   esac
+  key="$1"
+  case $key in
+    up)
+      shift # past argument
+      up "$@"
+      ;;
+    down)
+      shift # past argument
+      down "$@"
+      ;;
+    delete)
+      shift # past argument
+      delete "$@"
+      ;;
+    list)
+      list
+      ;;
+    status)
+      status
+      ;;
+    install)
+      shift # past argument
+      install "$@"
+      ;;
+    -h|--help)
+      help
+      ;;
+  esac
 else
-   help
+  help
 fi
